/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Student
 */
public class demo extends javax.swing.JFrame {

    /**
     * Creates new form demo
     */
    public demo() {
        initComponents();
    }
    
    Connection c;
    PreparedStatement p;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sellingprice = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        id = new javax.swing.JComboBox<>();
        loaddata = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        salesunit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        salesrevenue = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        unitvariablecost = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        totalvariablecost = new javax.swing.JTextField();
        contributionmarginpercentage = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        unitcontributionmargin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        totalcontributionmargin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        operatingincome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fixedcost = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 233, 231));
        setEnabled(false);
        setFocusable(false);

        jLabel13.setText("Product id");
        jLabel13.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setText("Selling Price");

        sellingprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellingpriceActionPerformed(evt);
            }
        });

        jLabel14.setText("Product Name");

        id.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                idItemStateChanged(evt);
            }
        });

        loaddata.setText("Load Data");
        loaddata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loaddataActionPerformed(evt);
            }
        });

        jLabel2.setText("Sales Unit");

        salesunit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                salesunitKeyReleased(evt);
            }
        });

        jLabel3.setText("Sales Revenue");

        jLabel16.setText("Unit Variable Cost");

        unitvariablecost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unitvariablecostKeyReleased(evt);
            }
        });

        jLabel4.setText("Total Variable Cost");

        totalvariablecost.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                totalvariablecostInputMethodTextChanged(evt);
            }
        });
        totalvariablecost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalvariablecostKeyReleased(evt);
            }
        });

        jLabel10.setText("Contribution Margin Percentage");

        jLabel5.setText("Unit Contribution Margin");

        jLabel6.setText("Total Contribution Margin");

        jLabel7.setText("Operating Income");

        jLabel8.setText("Fixed Cost");

        fixedcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixedcostActionPerformed(evt);
            }
        });
        fixedcost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fixedcostKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contributionmarginpercentage)
                            .addComponent(totalcontributionmargin)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fixedcost)
                            .addComponent(operatingincome)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(138, 138, 138)
                                .addComponent(unitcontributionmargin))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(163, 163, 163)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(productname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sellingprice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(salesunit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(salesrevenue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(163, 163, 163)
                                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(160, 160, 160)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(totalvariablecost, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                                                .addComponent(unitvariablecost)))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(253, 253, 253)
                .addComponent(loaddata)
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13)
                                            .addComponent(loaddata))
                                        .addGap(9, 9, 9)
                                        .addComponent(productname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel14))
                                .addGap(14, 14, 14)
                                .addComponent(sellingprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salesunit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salesrevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(unitvariablecost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(totalvariablecost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(unitcontributionmargin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(totalcontributionmargin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(contributionmarginpercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fixedcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(operatingincome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sellingpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellingpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellingpriceActionPerformed

    private void idItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_idItemStateChanged
        try {
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis", "root", "nclc123");
            p= c.prepareStatement("SELECT * FROM proinfo WHERE product_id = " + id.getSelectedItem().toString());

            ResultSet r = p.executeQuery();

            while(r.next()){

                productname.setText(r.getString(2));
                sellingprice.setText(String.valueOf(r.getDouble(3)));
            

            }

        } catch (Exception ex) {

        } // TODO add your handling code here:
    }//GEN-LAST:event_idItemStateChanged

    private void loaddataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loaddataActionPerformed
        String product_id = "";
        try {
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis", "root", "nclc123");
            p = c.prepareStatement("SELECT product_id FROM proinfo ");

            ResultSet r = p.executeQuery();

          id.removeAllItems();

            while(r.next()){
                product_id=r.getInt(1)+"\n";
          id.addItem(product_id);

            }

        } catch (Exception ex) {

        }        // TODO add your handling code here:
    }//GEN-LAST:event_loaddataActionPerformed

    private void salesunitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salesunitKeyReleased
        double selling_price = Double.valueOf(sellingprice.getText());
        int sales_unit  = Integer.valueOf(salesunit.getText());
         double sales_revenue = selling_price*sales_unit;
         String revenue= String.valueOf(sales_revenue);
         salesrevenue.setText(revenue);
         
// TODO add your handling code here:
    }//GEN-LAST:event_salesunitKeyReleased

    private void unitvariablecostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitvariablecostKeyReleased
       double selling_price = Double.valueOf(sellingprice.getText());
        double unit_variable_cost = Double.valueOf(unitvariablecost.getText());
        double total_variable_cost = selling_price * unit_variable_cost;
        String total_vc = String .valueOf(total_variable_cost);
        totalvariablecost.setText(total_vc);
        
        double unit_contribution_margin = selling_price-unit_variable_cost;
        String unit_cm = String.valueOf(unit_contribution_margin);
        unitcontributionmargin.setText(unit_cm);
        
        double sales_revenue= Double.valueOf(salesrevenue.getText());
        double total_contribution_margin = sales_revenue-unit_contribution_margin;
        String total_cm = String.valueOf(total_contribution_margin);
        totalcontributionmargin.setText(total_cm);
        
        double contribution_margin_percentage = (unit_contribution_margin/selling_price)*100;
        String cm_percentage = String.valueOf(contribution_margin_percentage);
        contributionmarginpercentage.setText(cm_percentage);
        
       // TODO add your handling code here:
    }//GEN-LAST:event_unitvariablecostKeyReleased

    private void totalvariablecostInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_totalvariablecostInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_totalvariablecostInputMethodTextChanged

    private void totalvariablecostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalvariablecostKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_totalvariablecostKeyReleased

    private void fixedcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixedcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fixedcostActionPerformed

    private void fixedcostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fixedcostKeyReleased
        int fixed_cost = Integer.valueOf(fixedcost.toString());
        double total_contribution_margin = Double.valueOf(totalcontributionmargin.toString());
        double operating_income = fixed_cost*total_contribution_margin;
        String opt_income = String.valueOf(operating_income);
        operatingincome.setText(opt_income);
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_fixedcostKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new demo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contributionmarginpercentage;
    private javax.swing.JTextField fixedcost;
    private javax.swing.JComboBox<String> id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton loaddata;
    private javax.swing.JTextField operatingincome;
    private javax.swing.JTextField productname;
    private javax.swing.JTextField salesrevenue;
    private javax.swing.JTextField salesunit;
    private javax.swing.JTextField sellingprice;
    private javax.swing.JTextField totalcontributionmargin;
    private javax.swing.JTextField totalvariablecost;
    private javax.swing.JTextField unitcontributionmargin;
    private javax.swing.JTextField unitvariablecost;
    // End of variables declaration//GEN-END:variables
}
