/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Student
 */
public class jhamelabidda extends javax.swing.JFrame {

    /**
     * Creates new form jhamelabidda
     */
    public jhamelabidda() {
        initComponents();
    }
    
    Connection c;
    PreparedStatement p;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalcontributionmargin = new javax.swing.JTextField();
        salesunit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        salesrevenue = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        unitvariablecost = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        totalvariablecost = new javax.swing.JTextField();
        contributionmarginpercentage = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        productname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sellingprice = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        id = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        unitcontributionmargin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        loaddata = new javax.swing.JButton();
        operatingincome = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fixedcost = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        incometaxpercentage = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        incometaxamount = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        netincome = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        SaveData = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        operatingleverage = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        bepunits = new javax.swing.JTextField();
        beprevenues = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        marginofsafety = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        marginofsafetypercent = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        whatifanalysis = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        salesunit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                salesunitKeyReleased(evt);
            }
        });

        jLabel3.setText("Sales Revenue");

        jLabel16.setText("Unit Variable Cost");

        unitvariablecost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unitvariablecostKeyReleased(evt);
            }
        });

        jLabel4.setText("Total Variable Cost");

        totalvariablecost.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                totalvariablecostInputMethodTextChanged(evt);
            }
        });
        totalvariablecost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalvariablecostKeyReleased(evt);
            }
        });

        jLabel10.setText("Contribution Margin Percentage");

        jLabel5.setText("Unit Contribution Margin");

        jLabel13.setText("Product id");
        jLabel13.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setText("Selling Price");

        sellingprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellingpriceActionPerformed(evt);
            }
        });

        jLabel14.setText("Product Name");

        id.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                idItemStateChanged(evt);
            }
        });

        jLabel2.setText("Sales Unit");

        jLabel6.setText("Total Contribution Margin");

        loaddata.setText("Load Data");
        loaddata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loaddataActionPerformed(evt);
            }
        });

        jLabel11.setText("Operating Income");

        fixedcost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fixedcostKeyReleased(evt);
            }
        });

        jLabel9.setText("Fixed Cost");

        incometaxpercentage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                incometaxpercentageKeyReleased(evt);
            }
        });

        jLabel12.setText("Income Tax Percentage");

        incometaxamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                incometaxamountKeyReleased(evt);
            }
        });

        jLabel15.setText("Income Tax ");

        netincome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                netincomeKeyReleased(evt);
            }
        });

        jLabel17.setText("Net Income");

        SaveData.setText("Save Data");
        SaveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveDataActionPerformed(evt);
            }
        });

        update.setText("Update Data");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jLabel7.setText("Operating Leverage");

        operatingleverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatingleverageActionPerformed(evt);
            }
        });

        jLabel8.setText("Break Even Point in Units");

        jLabel18.setText("Break Even Point in Revenues");

        jLabel19.setText("Margin of Safety");

        marginofsafety.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marginofsafetyActionPerformed(evt);
            }
        });

        jLabel20.setText("Margin of Safety Percentage");

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Log Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Data Show");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel21.setText("CVP Analysis");

        jButton5.setText("Sensitivity Analysis");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("New Product");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        whatifanalysis.setText("What if Analysis");
        whatifanalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whatifanalysisActionPerformed(evt);
            }
        });

        jButton7.setText("High Low Method");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel2)))
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel4))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(sellingprice, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(160, 160, 160)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(unitvariablecost)
                                                            .addComponent(totalcontributionmargin)
                                                            .addComponent(unitcontributionmargin)
                                                            .addComponent(totalvariablecost)
                                                            .addComponent(contributionmarginpercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(productname, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(160, 160, 160)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(salesunit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(salesrevenue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel17))
                                        .addGap(140, 140, 140)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(fixedcost, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(operatingincome, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(incometaxamount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(netincome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(incometaxpercentage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                                                    .addComponent(jLabel19))
                                                .addGap(111, 111, 111))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addGap(116, 116, 116)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(bepunits, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(operatingleverage, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(beprevenues, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(marginofsafety, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(marginofsafetypercent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(loaddata)
                                .addGap(108, 108, 108)
                                .addComponent(SaveData)
                                .addGap(97, 97, 97)
                                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(jButton3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(whatifanalysis)
                .addGap(71, 71, 71)
                .addComponent(jButton5)
                .addGap(75, 75, 75)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(320, 320, 320))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sellingprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salesunit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salesrevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unitvariablecost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4))
                            .addComponent(totalvariablecost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(unitcontributionmargin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(totalcontributionmargin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(contributionmarginpercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(fixedcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(operatingincome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(incometaxpercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(incometaxamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(netincome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(operatingleverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bepunits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(beprevenues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel19))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(marginofsafety, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel20))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(marginofsafetypercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loaddata)
                    .addComponent(SaveData)
                    .addComponent(update)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton6))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(whatifanalysis)
                    .addComponent(jButton2)
                    .addComponent(jButton7))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salesunitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salesunitKeyReleased
        double selling_price = Double.valueOf(sellingprice.getText());
        int sales_unit  = Integer.valueOf(salesunit.getText());
        double sales_revenue = selling_price*sales_unit;
        String revenue= String.valueOf(sales_revenue);
        salesrevenue.setText(revenue);

        // TODO add your handling code here:
    }//GEN-LAST:event_salesunitKeyReleased

    private void unitvariablecostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitvariablecostKeyReleased
        double selling_price = Double.valueOf(sellingprice.getText());
        double unit_variable_cost = Double.valueOf(unitvariablecost.getText());
        double total_variable_cost = selling_price * unit_variable_cost;
        String total_vc = String .valueOf(total_variable_cost);
        totalvariablecost.setText(total_vc);

        double unit_contribution_margin = selling_price-unit_variable_cost;
        String unit_cm = String.valueOf(unit_contribution_margin);
        unitcontributionmargin.setText(unit_cm);

        double sales_revenue= Double.valueOf(salesrevenue.getText());
        double total_contribution_margin = sales_revenue-unit_contribution_margin;
        String total_cm = String.valueOf(total_contribution_margin);
        totalcontributionmargin.setText(total_cm);

        double contribution_margin_percentage = (unit_contribution_margin/selling_price)*100;
        String cm_percentage = String.valueOf(contribution_margin_percentage);
        contributionmarginpercentage.setText(cm_percentage);

        // TODO add your handling code here:
    }//GEN-LAST:event_unitvariablecostKeyReleased

    private void totalvariablecostInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_totalvariablecostInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_totalvariablecostInputMethodTextChanged

    private void totalvariablecostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalvariablecostKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_totalvariablecostKeyReleased

    private void sellingpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellingpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellingpriceActionPerformed

    private void idItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_idItemStateChanged
        try {
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis", "root", "nclc123");
            p= c.prepareStatement("SELECT * FROM proinfo WHERE product_id = " + id.getSelectedItem().toString());

            ResultSet r = p.executeQuery();

            while(r.next()){

                productname.setText(r.getString(2));
                sellingprice.setText(String.valueOf(r.getDouble(3)));

            }
            salesunit.setText("");
            salesrevenue.setText("");
            unitvariablecost.setText("");
            totalvariablecost.setText("");
            unitcontributionmargin.setText("");
            totalcontributionmargin.setText("");
            contributionmarginpercentage.setText("");
            fixedcost.setText("");
            operatingincome.setText("");
            incometaxpercentage.setText("");
            incometaxamount.setText("");
            netincome.setText("");

        } catch (Exception ex) {

        } // TODO add your handling code here:
    }//GEN-LAST:event_idItemStateChanged

    private void loaddataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loaddataActionPerformed
        String product_id = "";
        try {
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis", "root", "nclc123");
            p = c.prepareStatement("SELECT product_id FROM proinfo ");

            ResultSet r = p.executeQuery();

            id.removeAllItems();

            while(r.next()){
                product_id=r.getInt(1)+"\n";
                id.addItem(product_id);

            }

        } catch (Exception ex) {

        }        // TODO add your handling code here:
    }//GEN-LAST:event_loaddataActionPerformed

    private void fixedcostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fixedcostKeyReleased
        double total_cm = Double.valueOf(totalcontributionmargin.getText());
        double fixed_cost= Double.valueOf(fixedcost.getText());
        double operate_income = total_cm-fixed_cost;
        String opt_income = String.valueOf(operate_income);
        operatingincome.setText(opt_income);
        
        String unit_contribution_margin = unitcontributionmargin.getText();
        double uCM = Double.parseDouble(unit_contribution_margin);
        
        int break_even_units = (int) (fixed_cost/uCM);
        String bepUnits = String.valueOf(break_even_units);
        bepunits.setText(bepUnits);
        
        String contributin_margin_ratio = contributionmarginpercentage.getText();
        double cmRatio = Double.parseDouble(contributin_margin_ratio);
        double break_even_revenues = fixed_cost/(cmRatio/100);
        String bepRevenues = String.valueOf(break_even_revenues);
        beprevenues.setText(bepRevenues);
        
        String sales_revenue = salesrevenue.getText();
        double sRevenue = Double.parseDouble(sales_revenue);
        double margin_of_safety = sRevenue-break_even_revenues;
        String safetyMargin = String.valueOf(margin_of_safety);
        marginofsafety.setText(safetyMargin);
        
        double margin_of_safety_ratio = (sRevenue-break_even_revenues)/sRevenue;
        String safetyMarginRatio = String.valueOf(margin_of_safety_ratio);
        marginofsafetypercent.setText(safetyMarginRatio);

        
        
// TODO add your handling code here:
    }//GEN-LAST:event_fixedcostKeyReleased

    private void incometaxpercentageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_incometaxpercentageKeyReleased
       
        double operating_income = Double.parseDouble(operatingincome.getText());
        double income_tax_percentage = Double.parseDouble(incometaxpercentage.getText());
      
       
        double income_tax_amount = operating_income*(income_tax_percentage/100);
        String income_tax = String.valueOf(income_tax_amount);
        incometaxamount.setText(income_tax);
        
        double net_income = operating_income-income_tax_amount;
        String income = String.valueOf(net_income);
        netincome.setText(income);
        
        String total_contribution_margin = totalcontributionmargin.getText();
        double totalCM = Double.parseDouble(total_contribution_margin);
        double operating_leverage = totalCM/net_income;
        String operatingLeverage = String.valueOf(operating_leverage);
        operatingleverage.setText(operatingLeverage);
        

// TODO add your handling code here:
    }//GEN-LAST:event_incometaxpercentageKeyReleased

    private void incometaxamountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_incometaxamountKeyReleased
//     double income_tax = Double.valueOf(incometaxamount.toString());
//double operating_income = Double.valueOf(operatingincome.toString());
//double net_income = operating_income - income_tax;
//String income = String.valueOf(net_income);
//netincome.setText(income);   // TODO add your handling code here:
    }//GEN-LAST:event_incometaxamountKeyReleased

    private void SaveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveDataActionPerformed
//        String pid = (String)id.getSelectedItem();
//        int prid = Integer.parseInt(pid);
        String pname = productname.getText();
        String sellPrice = sellingprice.getText();
        double sPrice = Double.parseDouble(sellPrice);
        String salesUnit = salesunit.getText();
        int sUnit = Integer.parseInt(salesUnit);
        String unit_variable_cost = unitvariablecost.getText();
        double unitVC = Double.parseDouble(unit_variable_cost);
        String total_variable_cost = totalvariablecost.getText();
        double totalVC = Double.parseDouble(total_variable_cost);
        String unit_contribution_margin = unitcontributionmargin.getText();
        double unitCM = Double.parseDouble(unit_contribution_margin);
        String total_contribution_margin = totalcontributionmargin.getText();
        double totalCM = Double.parseDouble(total_contribution_margin);
        String contribution_margin_percentage = contributionmarginpercentage.getText();
        double cmRatio = Double.parseDouble(contribution_margin_percentage);
        String totalFixedCost = fixedcost.getText();
        double totalFC = Double.parseDouble(totalFixedCost);
        String operatingIncome = operatingincome.getText();
        double oIncome = Double.parseDouble(operatingIncome);
        String incomeTaxPercentage = incometaxpercentage.getText();
        double iTaxPercent = Double.parseDouble(incomeTaxPercentage);
        String incomeTaxAmount = incometaxamount.getText();
        double iTaxAmount = Double.parseDouble(incomeTaxAmount);
        String netIncomeAmount = netincome.getText();
        double netIncome = Double.parseDouble(netIncomeAmount);
        String operatingLeverage = operatingleverage.getText();
        double oLeverage = Double.parseDouble(operatingLeverage);
        String break_even_units = bepunits.getText();
        int bepUnits = Integer.parseInt(break_even_units);
        String break_even_revenues = beprevenues.getText();
        double bepRevenues = Double.parseDouble(break_even_revenues);
        String margin_of_safety = marginofsafety.getText();
        double safetyMargin = Double.parseDouble(margin_of_safety);
        String margin_of_safety_percentage = marginofsafetypercent.getText();
        double safetyMarginPercent = Double.parseDouble(margin_of_safety_percentage);
        
        
        
        
        
        try{
            c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
            p = c.prepareStatement("INSERT INTO proddemo VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            
//            p.setInt(1, prid);
            p.setString(1, pname);
            p.setDouble(2, sPrice);
            p.setInt(3, sUnit);
            p.setDouble(4, unitVC);
            p.setDouble(5, totalVC);
            p.setDouble(6, unitCM);
            p.setDouble(7, totalCM);
            p.setDouble(8, cmRatio);
            p.setDouble(9, totalFC);
            p.setDouble(10, oIncome);
            p.setDouble(11, iTaxPercent);
            p.setDouble(12, iTaxAmount);
            p.setDouble(13, netIncome);
            p.setDouble(14, oLeverage);
            p.setInt(15, bepUnits);
            p.setDouble(16, bepRevenues);
            p.setDouble(17, safetyMargin);
            p.setDouble(18, safetyMarginPercent);
           
            
            
            p.executeUpdate();
            
        }catch(Exception e){
            
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveDataActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
           String pname = productname.getText();
        
        try{
            
       
        String sellPrice = sellingprice.getText();
        double sPrice = Double.parseDouble(sellPrice);
        
        
            c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
            p = c.prepareStatement("UPDATE proddemo SET selling_price =? WHERE product_name = '"+pname+"' ");
            
//            p.setInt(1, prid);
       
            p.setDouble(1, sPrice);
     
            
            p.executeUpdate();
            
        }catch(Exception e){
            
        } 
        try{
            
          
    String salesUnit = salesunit.getText();
        int sUnit = Integer.parseInt(salesUnit);
        
        
            c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
            p = c.prepareStatement("UPDATE proddemo SET sales_unit =? WHERE product_name = '"+pname+"' ");
            
//            p.setInt(1, prid);
       
            p.setInt(1, sUnit);
     
            
            p.executeUpdate();
            
        }catch(Exception e){
            
        }
         try{
            
          
    String unit_variable_cost = unitvariablecost.getText();
        double unitVC = Double.parseDouble(unit_variable_cost);
        
        
            c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
            p = c.prepareStatement("UPDATE proddemo SET unit_variable_cost =? WHERE product_name = '"+pname+"' ");

       
            p.setDouble(1, unitVC);
     
            
            p.executeUpdate();
            
        }catch(Exception e){
            
        }
         try{
            
          
     String total_variable_cost = totalvariablecost.getText();
        double totalVC = Double.parseDouble(total_variable_cost);
        
        
            c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
            p = c.prepareStatement("UPDATE proddemo SET total_variable_cost =? WHERE product_name = '"+pname+"' ");

       
            p.setDouble(1, totalVC);
     
            
            p.executeUpdate();
            
        }catch(Exception e){
            
        }
         try{
            
          
     String unit_contribution_margin = unitcontributionmargin.getText();
        double unitCM = Double.parseDouble(unit_contribution_margin);
        
        
            c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
            p = c.prepareStatement("UPDATE proddemo SET unit_contribution_margin =? WHERE product_name = '"+pname+"' ");

       
            p.setDouble(1, unitCM);
     
            
            p.executeUpdate();
            
        }catch(Exception e){
            
        }
         try{
        
     String total_contribution_margin = totalcontributionmargin.getText();
        double totalCM = Double.parseDouble(total_contribution_margin);
        
            c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
            p = c.prepareStatement("UPDATE proddemo SET total_contribution_margin =? WHERE product_name = '"+pname+"' ");

            p.setDouble(1, totalCM);
     
            p.executeUpdate();
            
        }catch(Exception e){
            
        }
         try{
        
       String contribution_margin_percentage = contributionmarginpercentage.getText();
        double cmRatio = Double.parseDouble(contribution_margin_percentage);
        
            c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
            p = c.prepareStatement("UPDATE proddemo SET contribution_margin_ratio =? WHERE product_name = '"+pname+"' ");

            p.setDouble(1, cmRatio);
     
            p.executeUpdate();
            
        }catch(Exception e){
            
        }
         try{
        
      String totalFixedCost = fixedcost.getText();
        double totalFC = Double.parseDouble(totalFixedCost);
        
            c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
            p = c.prepareStatement("UPDATE proddemo SET fixed_cost =? WHERE product_name = '"+pname+"' ");

            p.setDouble(1, totalFC);
     
            p.executeUpdate();
            
        }catch(Exception e){
            
        }
         try{
        
      String operatingIncome = operatingincome.getText();
        double oIncome = Double.parseDouble(operatingIncome);
        
            c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
            p = c.prepareStatement("UPDATE proddemo SET operating_income =? WHERE product_name = '"+pname+"' ");
            
            p.setDouble(1, oIncome);
     
            p.executeUpdate();
            
        }catch(Exception e){
            
        }
         try{
        
 String incomeTaxPercentage = incometaxpercentage.getText();
        double iTaxPercent = Double.parseDouble(incomeTaxPercentage);
        
            c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
            p = c.prepareStatement("UPDATE proddemo SET income_tax_percentage =? WHERE product_name = '"+pname+"' ");
            
            p.setDouble(1, iTaxPercent);
     
            p.executeUpdate();
            
        }catch(Exception e){
            
        }
          try{
        
 String incomeTaxAmount = incometaxamount.getText();
        double iTaxAmount = Double.parseDouble(incomeTaxAmount);
            c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
            p = c.prepareStatement("UPDATE proddemo SET income_tax_amount =? WHERE product_name = '"+pname+"' ");
            
            p.setDouble(1, iTaxAmount);
     
            p.executeUpdate();
            
        }catch(Exception e){
            
        }
          try{
        
 String netIncomeAmount = netincome.getText();
        double netIncome = Double.parseDouble(netIncomeAmount);
            c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
            p = c.prepareStatement("UPDATE proddemo SET net_income =? WHERE product_name = '"+pname+"' ");
            
            p.setDouble(1, netIncome);
     
            p.executeUpdate();
            
        }catch(Exception e){
            
        }
          try{
        
String operatingLeverage = operatingleverage.getText();
        double oLeverage = Double.parseDouble(operatingLeverage);
            c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
            p = c.prepareStatement("UPDATE proddemo SET operating_leverage =? WHERE product_name = '"+pname+"' ");
            
            p.setDouble(1, oLeverage);
     
            p.executeUpdate();
            
        }catch(Exception e){
            
        }
         try{
        
String break_even_units = bepunits.getText();
        int bepUnits = Integer.parseInt(break_even_units);
            c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
            p = c.prepareStatement("UPDATE proddemo SET break_even_point_units =? WHERE product_name = '"+pname+"' ");
            
            
            p.setInt(1, bepUnits);
     
            p.executeUpdate();
            
        }catch(Exception e){
            
        }
          try{
        
String break_even_revenues = beprevenues.getText();
        double bepRevenues = Double.parseDouble(break_even_revenues);
            c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
            p = c.prepareStatement("UPDATE proddemo SET break_even_point_revenues =? WHERE product_name = '"+pname+"' ");
            
            
            p.setDouble(1, bepRevenues);
     
            p.executeUpdate();
            
        }catch(Exception e){
            
        }
          try{
        
String margin_of_safety = marginofsafety.getText();
        double safetyMargin = Double.parseDouble(margin_of_safety);
            c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
            p = c.prepareStatement("UPDATE proddemo SET margin_of_safety =? WHERE product_name = '"+pname+"' ");
            
            
            p.setDouble(1, safetyMargin);
     
            p.executeUpdate();
            
        }catch(Exception e){
            
        }
           try{
        
   String margin_of_safety_percentage = marginofsafetypercent.getText();
        double safetyMarginPercent = Double.parseDouble(margin_of_safety_percentage);
            c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
            p = c.prepareStatement("UPDATE proddemo SET margin_of_safety_percentage =? WHERE product_name = '"+pname+"' ");
            
            
            p.setDouble(1, safetyMarginPercent);
     
            p.executeUpdate();
            
        }catch(Exception e){
            
        }
         //           String pname = productname.getText();
//        String sellPrice = sellingprice.getText();
//        double sPrice = Double.parseDouble(sellPrice);
//        String salesUnit = salesunit.getText();
//        int sUnit = Integer.parseInt(salesUnit);
//        String unit_variable_cost = unitvariablecost.getText();
//        double unitVC = Double.parseDouble(unit_variable_cost);
//        String total_variable_cost = totalvariablecost.getText();
//        double totalVC = Double.parseDouble(total_variable_cost);
//        String unit_contribution_margin = unitcontributionmargin.getText();
//        double unitCM = Double.parseDouble(unit_contribution_margin);
//        String total_contribution_margin = totalcontributionmargin.getText();
//        double totalCM = Double.parseDouble(total_contribution_margin);
//        String contribution_margin_percentage = contributionmarginpercentage.getText();
//        double cmRatio = Double.parseDouble(contribution_margin_percentage);
//        String totalFixedCost = fixedcost.getText();
//        double totalFC = Double.parseDouble(totalFixedCost);
//        String operatingIncome = operatingincome.getText();
//        double oIncome = Double.parseDouble(operatingIncome);
//        String incomeTaxPercentage = incometaxpercentage.getText();
//        double iTaxPercent = Double.parseDouble(incomeTaxPercentage);
//        String incomeTaxAmount = incometaxamount.getText();
//        double iTaxAmount = Double.parseDouble(incomeTaxAmount);
//        String netIncomeAmount = netincome.getText();
//        double netIncome = Double.parseDouble(netIncomeAmount);
//        String operatingLeverage = operatingleverage.getText();
//        double oLeverage = Double.parseDouble(operatingLeverage);
//        String break_even_units = bepunits.getText();
//        int bepUnits = Integer.parseInt(break_even_units);
//        String break_even_revenues = beprevenues.getText();
//        double bepRevenues = Double.parseDouble(break_even_revenues);
//        String margin_of_safety = marginofsafety.getText();
//        double safetyMargin = Double.parseDouble(margin_of_safety);
//        String margin_of_safety_percentage = marginofsafetypercent.getText();
//        double safetyMarginPercent = Double.parseDouble(margin_of_safety_percentage);
//        
//
         
// try{
//            
//          
//        
//        
//            c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
//            p = c.prepareStatement("UPDATE proddemo SET selling_price =?, sales_unit = ?, unit_variable_cost =? , total_variable_cost =?, unit_contribution_margin = ?, total_contribution_margin =?, contribution_margin_ratio=?, fixed_cost =?, operating_income = ?, income_tax_percentage = ? , income_tax_amount =? , net_income =? , operating_leverage =?, break_even_point_units =?, break_even_point_revenues =?, margin_of_safety =?, margin_of_safety_percentage =? WHERE product_name =? ");
//            
////            p.setInt(1, prid);
//       
//            p.setDouble(1, sPrice);
//     
//            p.setString(18, pname);
//           
//            
//            
//            p.executeUpdate();
//            
//        }catch(Exception e){
//            
//        } 
//        
//             p.setInt(2, sUnit);
//            p.setDouble(3, unitVC);
//            p.setDouble(4, totalVC);
//            p.setDouble(5, unitCM);
//            p.setDouble(6, totalCM);
//            p.setDouble(7, cmRatio);
//            p.setDouble(8, totalFC);
//            p.setDouble(9, oIncome);
//            p.setDouble(10, iTaxPercent);
//            p.setDouble(11, iTaxAmount);
//            p.setDouble(12, netIncome);
//            p.setDouble(13, oLeverage);
//            p.setInt(14, bepUnits);
//            p.setDouble(15, bepRevenues);
//            p.setDouble(16, safetyMargin);
//            p.setDouble(17, safetyMarginPercent);  
        
                // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void operatingleverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatingleverageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_operatingleverageActionPerformed

    private void netincomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_netincomeKeyReleased
           
        
        
        String total_contribution_margin = totalcontributionmargin.getText();
        double totalCM = Double.parseDouble(total_contribution_margin);
            String net_income_amount = netincome.getText();
            double netIncome = Double.parseDouble(net_income_amount);
        
        
        double operating_leverage = totalCM/netIncome;
        String operatingLeverage = String.valueOf(operating_leverage);
        operatingleverage.setText(operatingLeverage);    // TODO add your handling code here:
    }//GEN-LAST:event_netincomeKeyReleased

    private void marginofsafetyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marginofsafetyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marginofsafetyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String pname = productname.getText();
         try{
             c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
            p = c.prepareStatement("DELETE FROM proddemo WHERE product_name = '"+pname+"' ");
             p.executeUpdate();
            
         }catch(Exception e){
             
         }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    dispose();
    Login l = new Login();
l.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       TableShow t = new TableShow();
       t.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        NewProductEntry n = new NewProductEntry();
        n.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void whatifanalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whatifanalysisActionPerformed
        TargetIncome2 t = new TargetIncome2();
t.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_whatifanalysisActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        HighLowMethod l = new HighLowMethod();
        l.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        sensitivityAnalysis s= new sensitivityAnalysis();
s.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jhamelabidda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jhamelabidda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jhamelabidda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jhamelabidda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jhamelabidda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveData;
    private javax.swing.JTextField beprevenues;
    private javax.swing.JTextField bepunits;
    private javax.swing.JTextField contributionmarginpercentage;
    private javax.swing.JTextField fixedcost;
    private javax.swing.JComboBox<String> id;
    private javax.swing.JTextField incometaxamount;
    private javax.swing.JTextField incometaxpercentage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton loaddata;
    private javax.swing.JTextField marginofsafety;
    private javax.swing.JTextField marginofsafetypercent;
    private javax.swing.JTextField netincome;
    private javax.swing.JTextField operatingincome;
    private javax.swing.JTextField operatingleverage;
    private javax.swing.JTextField productname;
    private javax.swing.JTextField salesrevenue;
    private javax.swing.JTextField salesunit;
    private javax.swing.JTextField sellingprice;
    private javax.swing.JTextField totalcontributionmargin;
    private javax.swing.JTextField totalvariablecost;
    private javax.swing.JTextField unitcontributionmargin;
    private javax.swing.JTextField unitvariablecost;
    private javax.swing.JButton update;
    private javax.swing.JButton whatifanalysis;
    // End of variables declaration//GEN-END:variables
}
