/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;

/**
 *
 * @author Student
 */
public class sensitivityAnalysis extends javax.swing.JFrame {

    /**
     * Creates new form sensitivityAnalysis
     */
    public sensitivityAnalysis() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        decreasepercentsp = new javax.swing.JTextField();
        increasepercentsp = new javax.swing.JTextField();
        increaseamountsp = new javax.swing.JTextField();
        decreaseamountsv = new javax.swing.JTextField();
        decreasepercentvc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        increasepercentvc = new javax.swing.JTextField();
        increaseamountvc = new javax.swing.JTextField();
        decreaseamountvc = new javax.swing.JTextField();
        decreasepercentfc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        increasepercentfc = new javax.swing.JTextField();
        increaseamountfc = new javax.swing.JTextField();
        decreaseamountfc = new javax.swing.JTextField();
        decreasepercentsv = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        increasepercentsv = new javax.swing.JTextField();
        increaseamountsv = new javax.swing.JTextField();
        decreaseamountsp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        basevc = new javax.swing.JTextField();
        basesv = new javax.swing.JTextField();
        basesp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        currentfc = new javax.swing.JTextField();
        currentvc = new javax.swing.JTextField();
        currentsv = new javax.swing.JTextField();
        currentsp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        productname = new javax.swing.JTextField();
        basefc = new javax.swing.JTextField();
        currentnetincome = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        basenetincome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Selling Price ");

        jLabel2.setText("Increase");

        jLabel3.setText("Decrease");

        jLabel4.setText("Change By percentage");

        jLabel5.setText("Increase");

        jLabel6.setText("Decrease");

        jLabel7.setText("Change By Amount");

        decreasepercentsp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                decreasepercentspKeyReleased(evt);
            }
        });

        increasepercentsp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                increasepercentspKeyReleased(evt);
            }
        });

        increaseamountsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseamountspActionPerformed(evt);
            }
        });
        increaseamountsp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                increaseamountspKeyReleased(evt);
            }
        });

        decreaseamountsv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                decreaseamountsvKeyReleased(evt);
            }
        });

        decreasepercentvc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreasepercentvcActionPerformed(evt);
            }
        });
        decreasepercentvc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                decreasepercentvcKeyReleased(evt);
            }
        });

        jLabel8.setText("Variable Cost");

        increasepercentvc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                increasepercentvcKeyReleased(evt);
            }
        });

        increaseamountvc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseamountvcActionPerformed(evt);
            }
        });
        increaseamountvc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                increaseamountvcKeyReleased(evt);
            }
        });

        decreaseamountvc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                decreaseamountvcKeyReleased(evt);
            }
        });

        decreasepercentfc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                decreasepercentfcKeyReleased(evt);
            }
        });

        jLabel9.setText("Fixed Cost");

        increasepercentfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increasepercentfcActionPerformed(evt);
            }
        });
        increasepercentfc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                increasepercentfcKeyReleased(evt);
            }
        });

        increaseamountfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseamountfcActionPerformed(evt);
            }
        });
        increaseamountfc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                increaseamountfcKeyReleased(evt);
            }
        });

        decreaseamountfc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                decreaseamountfcKeyReleased(evt);
            }
        });

        decreasepercentsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreasepercentsvActionPerformed(evt);
            }
        });
        decreasepercentsv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                decreasepercentsvKeyReleased(evt);
            }
        });

        jLabel10.setText("Sales Volume");

        increasepercentsv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                increasepercentsvKeyReleased(evt);
            }
        });

        increaseamountsv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                increaseamountsvKeyReleased(evt);
            }
        });

        decreaseamountsp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                decreaseamountspKeyReleased(evt);
            }
        });

        jLabel11.setText("Base ");

        basesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basespActionPerformed(evt);
            }
        });

        jLabel12.setText("Current");

        currentfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentfcActionPerformed(evt);
            }
        });

        currentsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentspActionPerformed(evt);
            }
        });

        jLabel13.setText("Product Name");

        productname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productnameKeyReleased(evt);
            }
        });

        basefc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basefcActionPerformed(evt);
            }
        });

        jLabel14.setText("Net Income");

        jButton1.setText("Calculate Net Income");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel15.setText("Sensitivity Analysis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(productname, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(264, 264, 264)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(165, 165, 165)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(87, 87, 87)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(107, 107, 107)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(increasepercentfc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(increasepercentsp, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(increasepercentvc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(increasepercentsv, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(decreasepercentsp)
                                            .addComponent(decreasepercentvc)
                                            .addComponent(decreasepercentsv)
                                            .addComponent(decreasepercentfc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(62, 62, 62)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(increaseamountsv, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(increaseamountsp, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(increaseamountvc, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(increaseamountfc, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(58, 58, 58)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(decreaseamountvc)
                                            .addComponent(decreaseamountfc)
                                            .addComponent(decreaseamountsp, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(decreaseamountsv, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(140, 140, 140))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(168, 168, 168)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(basenetincome)
                                    .addGap(74, 74, 74)
                                    .addComponent(currentnetincome, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(basesv)
                                        .addComponent(basesp)
                                        .addComponent(basevc)
                                        .addComponent(basefc, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(80, 80, 80)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(currentvc, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(currentsp, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(currentsv, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(currentfc, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(increaseamountsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(basesv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(currentsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(decreasepercentsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(increasepercentsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(decreaseamountsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(decreasepercentsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(increasepercentsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(increaseamountsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(basesp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(currentsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(decreaseamountsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(decreasepercentvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(increasepercentvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(increaseamountvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(basevc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(currentvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(decreaseamountvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(decreasepercentfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(increasepercentfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(increaseamountfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(currentfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(basefc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(decreaseamountfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(currentnetincome, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(basenetincome, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addComponent(jButton1)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection c ;
PreparedStatement p;

    public void base(){
//        String baseSV = basesv.getText();
//        String baseSP = basesp.getText();
//        String baseVC = basevc.getText();
//        String baseFC = basefc.getText();
//       
//        productname.setText("");
        
           String pname = productname.getText(); 
// 

       
       try{
           c= DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis","root","nclc123");
           p= c.prepareStatement("SELECT sales_unit, selling_price, unit_variable_cost, fixed_cost FROM proddemo WHERE product_name ='"+pname+"' ");
           
           ResultSet r= p.executeQuery();
           
           while(r.next()){
              
               
            int  salesVolueme1 = r.getInt(1);
            basesv.setText(String.valueOf(salesVolueme1));
            
             double sellingPrice1 = r.getDouble(2);
             basesp.setText(String.valueOf(sellingPrice1));
             
             double variableCost1 = r.getDouble(3);
             basevc.setText(String.valueOf(variableCost1));
             
             double fixedCost = r.getDouble(4);
             basefc.setText(String.valueOf(fixedCost));
            
           }
           
      
           
           
           
       }catch(Exception e){
           
       }
       
        
        
    }
    
    private void basespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basespActionPerformed

    private void decreasepercentsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreasepercentsvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decreasepercentsvActionPerformed

    private void increaseamountspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseamountspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_increaseamountspActionPerformed

    private void decreasepercentvcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreasepercentvcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decreasepercentvcActionPerformed

    private void increaseamountvcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseamountvcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_increaseamountvcActionPerformed

    private void increasepercentfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increasepercentfcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_increasepercentfcActionPerformed

    private void increaseamountfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseamountfcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_increaseamountfcActionPerformed

    private void currentfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentfcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentfcActionPerformed

    private void currentspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentspActionPerformed

    private void productnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productnameKeyReleased
        base();// TODO add your handling code here:
    }//GEN-LAST:event_productnameKeyReleased

    private void basefcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basefcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basefcActionPerformed

    private void increasepercentsvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_increasepercentsvKeyReleased
        String ipsv = increasepercentsv.getText();
        double increasePercentSV = Double.parseDouble(ipsv);
        

        
 String baseSV = basesv.getText();
 double basesalesVolume = Double.valueOf(baseSV);

double currSV = ((increasePercentSV/100) * basesalesVolume)+ basesalesVolume ;
       String currentSalesVolume= String.valueOf(currSV);
       currentsv.setText(currentSalesVolume);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_increasepercentsvKeyReleased

    private void increasepercentspKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_increasepercentspKeyReleased
                String ipsp = increasepercentsp.getText();
        double increasePercentSP = Double.parseDouble(ipsp);
        
                String baseSP = basesp.getText();
                double basesellingPrice = Double.parseDouble(baseSP);

       double currSP = ((increasePercentSP/100) * basesellingPrice)+ basesellingPrice;
       String currentSellingPrice= String.valueOf(currSP);
       currentsp.setText(currentSellingPrice);
       



// TODO add your handling code here:
    }//GEN-LAST:event_increasepercentspKeyReleased

    private void increasepercentvcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_increasepercentvcKeyReleased
              String ipvc = increasepercentvc.getText();
        double increasePercentVC = Double.parseDouble(ipvc); 
        
         String baseVC = basevc.getText();
              double basevariableCost = Double.parseDouble(baseVC);
              
              double currVC = ((increasePercentVC/100)*basevariableCost)+basevariableCost;
              String currentVariableCost = String.valueOf(currVC);
              currentvc.setText(currentVariableCost);

// TODO add your handling code here:
    }//GEN-LAST:event_increasepercentvcKeyReleased

    private void increasepercentfcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_increasepercentfcKeyReleased
                String ipfc = increasepercentfc.getText();
        double increasePercentFC = Double.parseDouble(ipfc);
        
          String baseFC = basefc.getText();
          double basefixedCost = Double.parseDouble(baseFC);
                 
             double currFC = ((increasePercentFC/100)*basefixedCost)+basefixedCost;
              String currentFixedCost = String.valueOf(currFC);
              currentfc.setText(currentFixedCost);


// TODO add your handling code here:
    }//GEN-LAST:event_increasepercentfcKeyReleased

    private void decreasepercentsvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_decreasepercentsvKeyReleased
        String dpsv = decreasepercentsv.getText();
        double decreasePercentSV = Double.parseDouble(dpsv);
        
 String baseSV = basesv.getText();
 double basesalesVolume = Double.valueOf(baseSV);

double currSV = basesalesVolume-((decreasePercentSV/100) * basesalesVolume) ;
       String currentSalesVolume= String.valueOf(currSV);
       currentsv.setText(currentSalesVolume);// TODO add your handling code here:
    }//GEN-LAST:event_decreasepercentsvKeyReleased

    private void decreasepercentspKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_decreasepercentspKeyReleased
        String dpsp = decreasepercentsp.getText();
        double decreasePercentSP = Double.parseDouble(dpsp);
        
        String baseSP = basesp.getText();
        double basesellingPrice = Double.parseDouble(baseSP);

       double currSP = basesellingPrice-((decreasePercentSP/100) * basesellingPrice) ;
       String currentSellingPrice= String.valueOf(currSP);
       currentsp.setText(currentSellingPrice);// TODO add your handling code here:
    }//GEN-LAST:event_decreasepercentspKeyReleased

    private void decreasepercentvcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_decreasepercentvcKeyReleased
       String dpvc = decreasepercentvc.getText();
        double decreasePercentVC = Double.parseDouble(dpvc); 
        
         String baseVC = basevc.getText();
              double basevariableCost = Double.parseDouble(baseVC);
              
              double currVC = basevariableCost-((decreasePercentVC/100)*basevariableCost);
              String currentVariableCost = String.valueOf(currVC);
              currentvc.setText(currentVariableCost);
 // TODO add your handling code here:
    }//GEN-LAST:event_decreasepercentvcKeyReleased

    private void decreasepercentfcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_decreasepercentfcKeyReleased
          String dpfc = decreasepercentfc.getText();
        double decreasePercentFC = Double.parseDouble(dpfc);
        
          String baseFC = basefc.getText();
          double basefixedCost = Double.parseDouble(baseFC);
                 
          double currFC = basefixedCost-((decreasePercentFC/100)*basefixedCost);
              String currentFixedCost = String.valueOf(currFC);
              currentfc.setText(currentFixedCost);
// TODO add your handling code here:
    }//GEN-LAST:event_decreasepercentfcKeyReleased

    private void increaseamountsvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_increaseamountsvKeyReleased
        String iasv = increaseamountsv.getText();
        double increaseAmountSV = Double.parseDouble(iasv);
        

        
 String baseSV = basesv.getText();
double basesalesVolume = Double.valueOf(baseSV);

double currSV = increaseAmountSV + basesalesVolume ;
       String currentSalesVolume= String.valueOf(currSV);
       currentsv.setText(currentSalesVolume); // TODO add your handling code here:
    }//GEN-LAST:event_increaseamountsvKeyReleased

    private void increaseamountspKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_increaseamountspKeyReleased
        String iasp = increaseamountsp.getText();
        double increaseAmountSP = Double.parseDouble(iasp);
        
        String baseSP = basesp.getText();
 double baseSellingPrice = Double.valueOf(baseSP);

double currSP = increaseAmountSP + baseSellingPrice ;
       String currentSellingPrice= String.valueOf(currSP);
       currentsp.setText(currentSellingPrice); // TODO add your handling code here:
    }//GEN-LAST:event_increaseamountspKeyReleased

    private void increaseamountvcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_increaseamountvcKeyReleased
        String iavc = increaseamountvc.getText();
        double increaseAmountVC = Double.parseDouble(iavc);
                
 String baseVC = basevc.getText();
 double baseVariableCost = Double.valueOf(baseVC);

double currVC = increaseAmountVC + baseVariableCost ;
       String currentVariableCost= String.valueOf(currVC);
       currentvc.setText(currentVariableCost); // TODO add your handling code here:
    }//GEN-LAST:event_increaseamountvcKeyReleased

    private void increaseamountfcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_increaseamountfcKeyReleased
         String iafc = increaseamountfc.getText();
        double increaseAmountFC = Double.parseDouble(iafc);
        
 String baseFC = basefc.getText();
double baseFixedCost = Double.valueOf(baseFC);

double currFC = increaseAmountFC + baseFixedCost ;
       String currentFixedCost= String.valueOf(currFC);
       currentfc.setText(currentFixedCost);// TODO add your handling code here:
    }//GEN-LAST:event_increaseamountfcKeyReleased

    private void decreaseamountsvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_decreaseamountsvKeyReleased
          String dasv = decreaseamountsv.getText();
        double decreaseAmountSV = Double.parseDouble(dasv);
        
 String baseSV = basesv.getText();
 double basesalesVolume = Double.valueOf(baseSV);

double currSV =  basesalesVolume-decreaseAmountSV  ;
       String currentSalesVolume= String.valueOf(currSV);
       currentsv.setText(currentSalesVolume);// TODO add your handling code here:
    }//GEN-LAST:event_decreaseamountsvKeyReleased

    private void decreaseamountspKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_decreaseamountspKeyReleased
         String dasp = decreaseamountsp.getText();
        double decreaseAmountSP = Double.parseDouble(dasp);
        
        String baseSP = basesp.getText();
 double baseSellingPrice = Double.valueOf(baseSP);

double currSP =  baseSellingPrice -decreaseAmountSP  ;
       String currentSellingPrice= String.valueOf(currSP);
       currentsp.setText(currentSellingPrice); // TODO add your handling code here:
    }//GEN-LAST:event_decreaseamountspKeyReleased

    private void decreaseamountvcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_decreaseamountvcKeyReleased
      String davc = decreaseamountvc.getText();
        double decreaseAmountVC = Double.parseDouble(davc);
                
 String baseVC = basevc.getText();
 double baseVariableCost = Double.valueOf(baseVC);

double currVC =  baseVariableCost-decreaseAmountVC  ;
       String currentVariableCost= String.valueOf(currVC);
       currentvc.setText(currentVariableCost);  // TODO add your handling code here:
    }//GEN-LAST:event_decreaseamountvcKeyReleased

    private void decreaseamountfcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_decreaseamountfcKeyReleased
       String dafc = decreaseamountfc.getText();
        double decreaseAmountFC = Double.parseDouble(dafc);
        
 String baseFC = basefc.getText();
 double baseFixedCost = Double.valueOf(baseFC);

double currFC =  baseFixedCost-decreaseAmountFC ;
       String currentFixedCost= String.valueOf(currFC);
       currentfc.setText(currentFixedCost); // TODO add your handling code here:
    }//GEN-LAST:event_decreaseamountfcKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String bSV = basesv.getText();
        String bSP = basesp.getText();
        String bVC = basevc.getText();
        String bFC = basefc.getText();
        
        Double baseSV = Double.parseDouble(bSV);
        Double baseSP = Double.parseDouble(bSP);
        Double baseVC = Double.parseDouble(bVC);
        Double baseFC = Double.parseDouble(bFC);
        
        Double bNI = (baseSV * baseSP) - baseVC - baseFC;
        String baseNetIncome = String.valueOf(bNI);
        basenetincome.setText(baseNetIncome);
        
        String cSV = currentsv.getText();
        String cSP = currentsp.getText();
        String cVC =  currentvc.getText();
        String cFC =  currentfc.getText();
        
        Double currSV = Double.parseDouble(cSV);
        Double currSP = Double.parseDouble(cSP);
        Double currVC = Double.parseDouble(cVC);
        Double currFC = Double.parseDouble(cFC);
        
        Double cNI = (currSV * currSP) - currVC - currFC;
        String currentNetIncome = String.valueOf(cNI);
       currentnetincome.setText(currentNetIncome);
        
        
        
        
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sensitivityAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sensitivityAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sensitivityAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sensitivityAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sensitivityAnalysis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField basefc;
    private javax.swing.JTextField basenetincome;
    private javax.swing.JTextField basesp;
    private javax.swing.JTextField basesv;
    private javax.swing.JTextField basevc;
    private javax.swing.JTextField currentfc;
    private javax.swing.JTextField currentnetincome;
    private javax.swing.JTextField currentsp;
    private javax.swing.JTextField currentsv;
    private javax.swing.JTextField currentvc;
    private javax.swing.JTextField decreaseamountfc;
    private javax.swing.JTextField decreaseamountsp;
    private javax.swing.JTextField decreaseamountsv;
    private javax.swing.JTextField decreaseamountvc;
    private javax.swing.JTextField decreasepercentfc;
    private javax.swing.JTextField decreasepercentsp;
    private javax.swing.JTextField decreasepercentsv;
    private javax.swing.JTextField decreasepercentvc;
    private javax.swing.JTextField increaseamountfc;
    private javax.swing.JTextField increaseamountsp;
    private javax.swing.JTextField increaseamountsv;
    private javax.swing.JTextField increaseamountvc;
    private javax.swing.JTextField increasepercentfc;
    private javax.swing.JTextField increasepercentsp;
    private javax.swing.JTextField increasepercentsv;
    private javax.swing.JTextField increasepercentvc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField productname;
    // End of variables declaration//GEN-END:variables
}
