/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Student
 */
public class TableShow extends javax.swing.JFrame {

    /**
     * Creates new form TableShow
     */
    public TableShow() {
        initComponents();
        table();
    }
    Connection c;
    PreparedStatement p;
    
    DefaultTableModel t = new DefaultTableModel();
     public void table(){
     
       t.addColumn(" selling price ");
       t.addColumn("sales unit");
       t.addColumn("unit variable cost");
       t.addColumn("total variable cost");
       t.addColumn("unit contribution margin");
       t.addColumn("total contribution margin");
       t.addColumn("contribution margin ratio");
       t.addColumn("fixed cost");
       t.addColumn("operating income");
       t.addColumn("income tax percent");
       t.addColumn("income tax amount");
       t.addColumn("net income");
       t.addColumn("operating leverage");
       t.addColumn("break even units");
       t.addColumn("break even revenues");
       t.addColumn("margin of safety");
       t.addColumn("margin of safety percent");
       
       
       tab.setModel(t);
       
      int i = t.getRowCount();
        for (int j = i-1; j >= 0; j--) {
            t.removeRow(j);
        }
       try{
           c = DriverManager.getConnection("jdbc:mysql://localhost:3306/cvpanalysis", "root", "nclc123");
            p = c.prepareStatement("SELECT * FROM proddemo");
//       
            ResultSet r = p.executeQuery();
            while (r.next()) {               
               Vector v = new Vector();
               v.add(r.getString(1));
               v.add(r.getString(2));
               v.add(r.getString(3));
               v.add(r.getString(4));
               v.add(r.getString(5));
               v.add(r.getString(6));
               v.add(r.getString(7));
               v.add(r.getString(8));
               v.add(r.getString(9));
               v.add(r.getString(10));
               v.add(r.getString(11));
               v.add(r.getString(12));
               v.add(r.getString(13));
               v.add(r.getString(14));
               v.add(r.getString(15));
               v.add(r.getString(16));
               v.add(r.getString(17));
               t.addRow(v);
            
            }
            
       }catch(Exception e){
           
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1265, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableShow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
