/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

/**
 *
 * @author Student
 */
public class TargetIncome extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TargetIncome() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fixedcost = new javax.swing.JTextField();
        targetincome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        unitcontributionmargin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        salesunit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        salesrevenues = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sellingprice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("What if Analysis");

        jLabel2.setText("Fixed Cost");

        fixedcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixedcostActionPerformed(evt);
            }
        });
        fixedcost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fixedcostKeyReleased(evt);
            }
        });

        targetincome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                targetincomeKeyReleased(evt);
            }
        });

        jLabel3.setText("Target Income");

        unitcontributionmargin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                unitcontributionmarginPropertyChange(evt);
            }
        });
        unitcontributionmargin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unitcontributionmarginKeyReleased(evt);
            }
        });

        jLabel4.setText("Unit Contribution Margin");

        salesunit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                salesunitKeyReleased(evt);
            }
        });

        jLabel5.setText("Sales Unit");

        jLabel6.setText("Sales Revenue");

        sellingprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sellingpriceKeyReleased(evt);
            }
        });

        jLabel7.setText("Selling Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(147, 147, 147))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(94, 94, 94)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(salesunit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                            .addComponent(unitcontributionmargin, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fixedcost, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(targetincome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sellingprice, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel6)
                .addGap(143, 143, 143)
                .addComponent(salesrevenues, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fixedcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(targetincome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(unitcontributionmargin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(salesunit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sellingprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(salesrevenues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fixedcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixedcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fixedcostActionPerformed

    private void salesunitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salesunitKeyReleased
//        String fc = fixedcost.getText();
//        String ni = TargetIncome.getText();
//        String ucm = unitcontributionmargin.getText();
//
//        double fixedCost = Double.parseDouble(fc);
//        double netIncome = Double.parseDouble(ni);
//        double unitCM = Double.parseDouble(ucm);
//        
//        double sUnit = (fixedCost+netIncome)/unitCM;
//        String salesUnit = String.valueOf(sUnit);
//        salesunit.setText(salesUnit);
//        
        // TODO add your handling code here:
    }//GEN-LAST:event_salesunitKeyReleased

    private void fixedcostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fixedcostKeyReleased
//         String fc = fixedcost.getText();
//     
//        double fixedCost = Double.parseDouble(fc);
//        double sUnit = fixedCost;
//        String salesUnit = String.valueOf(sUnit);
//        salesunit.setText(salesUnit);
        // TODO add your handling code here:
    }//GEN-LAST:event_fixedcostKeyReleased

    private void targetincomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_targetincomeKeyReleased
//        String fc = fixedcost.getText();
//        String ni = TargetIncome.getText();
//     
//
//        double fixedCost = Double.parseDouble(fc);
//        double netIncome = Double.parseDouble(ni);
//
//        
//        double sUnit = (fixedCost+netIncome);
//        String salesUnit = String.valueOf(sUnit);
//        salesunit.setText(salesUnit);// TODO add your handling code here:
    }//GEN-LAST:event_targetincomeKeyReleased

    private void unitcontributionmarginPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_unitcontributionmarginPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_unitcontributionmarginPropertyChange

    private void unitcontributionmarginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitcontributionmarginKeyReleased
         String fc = fixedcost.getText();
        String ni = targetincome.getText();
        String ucm = unitcontributionmargin.getText();

        double fixedCost = Double.parseDouble(fc);
        double netIncome = Double.parseDouble(ni);
        double unitCM = Double.parseDouble(ucm);
        
        double sUnit = (fixedCost+netIncome)/unitCM;
        String salesUnit = String.valueOf(sUnit);
        salesunit.setText(salesUnit);// TODO add your handling code here:
    }//GEN-LAST:event_unitcontributionmarginKeyReleased

    private void sellingpriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sellingpriceKeyReleased
        String sUnit = salesunit.getText();
        String sPrice = sellingprice.getText();
        
        double salesUnit = Double.parseDouble(sUnit);
        double sellingPrice = Double.parseDouble(sPrice);
        
        double sRevenue = salesUnit*sellingPrice;
        String salesRevenue = String.valueOf(sRevenue);
        salesrevenues.setText(salesRevenue);

        // TODO add your handling code here:
    }//GEN-LAST:event_sellingpriceKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TargetIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TargetIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TargetIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TargetIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TargetIncome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fixedcost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField salesrevenues;
    private javax.swing.JTextField salesunit;
    private javax.swing.JTextField sellingprice;
    private javax.swing.JTextField targetincome;
    private javax.swing.JTextField unitcontributionmargin;
    // End of variables declaration//GEN-END:variables
}
